print("Heyy Annie")
print("I am learning Git")
print("Another Change")
print("Hello from main branch")
print("Hello from git conflict branch")
print("Caluclator Feature")
print("Learning GitHub Page")